# Generated by Django 3.2.5 on 2021-07-05 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210705_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
